### ISSUE TITLE
Progress bar for long operations

### ISSUE THREAD

**Issue by Kvel2D** [altlinux/admc#197]
Example: moving 3k users. Open modal dialog with progress bar. Also perform operations in separate thread to keep GUI thread running. Progress bar dialog is there to let user know what's going on and also block actions.

Open dialog only if operation actually takes a long time.

**Comment by iv-m** [comment]
One of the usual remedies for the UI freezes caused by long-running loops is calling `QCoreApplication::processEvents` from time to time from that loop. This may be less effective than threads-based solution, but is usually much easier to implement. Have you considered something like that?

By the way, `QEventLoop::ExcludeUserInputEvents` seems to be appropriate for this case.

**Comment by Kvel2D** [comment]
I've had some bad experiences with processEvents() before, so I'm leaning towards threads or other solutions. Also, LDAP has built-in asynchronous functions so I might use that.

**Comment by Kvel2D** [comment]
Too complicated.
